-- Auto-generated by scripts/generate_padding_fceux_targets.py.
-- Targets expect patched PRG bytes from the padding experiment strategy: preserve_tail.
return {
  { label = "padding_preserve_tail_rom_071a4_candidate_82", category = "능력치", rom = 0x071A4, start = 0xB192, stop = 0xB19C, bytes = "87 88 AA", old_bytes = "93 88 AA", source = "ちから", korean = "힘", strategy = "preserve_tail" },
}
