-- Auto-generated by scripts/generate_broad_scan_fceux_targets.py.
-- Targets expect original bytes for broad-scan promotion candidates.
-- Use on the base ROM first; do not treat hits as patch approval without screen context.
return {
  { label = "broad_0440c_kajiya", category = "스테이지", rom = 0x0440C, start = 0x83FC, stop = 0x83FE, bytes = "CA D0 E9", old_bytes = "CA D0 E9", source = "かじや", romaji = "Kajiya", korean = "대장간", confidence = "medium" },
  { label = "broad_048f4_tatsuji", category = "보스", rom = 0x048F4, start = 0x88E4, stop = 0x88E6, bytes = "07 09 03", old_bytes = "07 09 03", source = "たつじ", romaji = "Tatsuji", korean = "타츠지", confidence = "medium" },
  { label = "broad_052a5_tatsuji", category = "보스", rom = 0x052A5, start = 0x9295, stop = 0x9297, bytes = "82 84 7E", old_bytes = "82 84 7E", source = "たつじ", romaji = "Tatsuji", korean = "타츠지", confidence = "medium" },
  { label = "broad_05be5_tatsuji", category = "보스", rom = 0x05BE5, start = 0x9BD5, stop = 0x9BD7, bytes = "97 99 93", old_bytes = "97 99 93", source = "たつじ", romaji = "Tatsuji", korean = "타츠지", confidence = "medium" },
  { label = "broad_06294_heishichi", category = "보스", rom = 0x06294, start = 0xA284, stop = 0xA287, bytes = "9D 82 8C 91", old_bytes = "9D 82 8C 91", source = "へいしち", romaji = "Heishichi", korean = "헤이시치", confidence = "high" },
  { label = "broad_0631b_heishichi", category = "보스", rom = 0x0631B, start = 0xA30B, stop = 0xA30E, bytes = "9D 82 8C 91", old_bytes = "9D 82 8C 91", source = "へいしち", romaji = "Heishichi", korean = "헤이시치", confidence = "high" },
  { label = "broad_06359_heishichi", category = "보스", rom = 0x06359, start = 0xA349, stop = 0xA34C, bytes = "9D 82 8C 91", old_bytes = "9D 82 8C 91", source = "へいしち", romaji = "Heishichi", korean = "헤이시치", confidence = "high" },
}
