-- Auto-generated by scripts/generate_padding_fceux_targets.py.
-- Targets expect patched PRG bytes from the padding experiment strategy: pad_7a.
return {
  { label = "padding_pad_7a_rom_071a4_candidate_82", category = "능력치", rom = 0x071A4, start = 0xB192, stop = 0xB19C, bytes = "87 7A 7A", old_bytes = "93 88 AA", source = "ちから", korean = "힘", strategy = "pad_7a" },
}
