-- Auto-generated by scripts/generate_padding_fceux_targets.py.
-- Targets expect patched PRG bytes from the padding experiment strategy: pad_f8f9.
return {
  { label = "padding_pad_f8f9_rom_071a4_candidate_82", category = "능력치", rom = 0x071A4, start = 0xB192, stop = 0xB19C, bytes = "87 F8 F9", old_bytes = "93 88 AA", source = "ちから", korean = "힘", strategy = "pad_f8f9" },
}
