-- Auto-generated by scripts/generate_v04_fceux_targets.py.
-- Targets expect patched PRG bytes from the v0.4 equal-length static experiment.
return {
  { label = "v04_watch_rom_0561a_스테이지_7c", category = "스테이지", rom = 0x0561A, start = 0x95BE, stop = 0x960F, bytes = "8B 8C", old_bytes = "96 88", source = "はし", korean = "다리" },
  { label = "v04_watch_rom_0562f_보스_80", category = "보스", rom = 0x0562F, start = 0x961A, stop = 0x9623, bytes = "89 98 8E 90", old_bytes = "90 92 82 91", source = "たついち", korean = "타츠이치" },
  { label = "v04_watch_rom_05643_보스_80", category = "보스", rom = 0x05643, start = 0x9633, stop = 0x9637, bytes = "8D 8E 8F 90", old_bytes = "9D 82 8C 91", source = "へいしち", korean = "헤이시치" },
  { label = "v04_watch_rom_0569d_스테이지_7a", category = "스테이지", rom = 0x0569D, start = 0x968C, stop = 0x968F, bytes = "8B 8C", old_bytes = "A0 92", source = "はし", korean = "다리" },
  { label = "v04_watch_rom_056da_스테이지_80", category = "스테이지", rom = 0x056DA, start = 0x96C5, stop = 0x96CE, bytes = "8B 8C", old_bytes = "9A 8C", source = "はし", korean = "다리" },
  { label = "v04_watch_rom_0571c_스테이지_78", category = "스테이지", rom = 0x0571C, start = 0x9706, stop = 0x9714, bytes = "8B 8C", old_bytes = "92 84", source = "はし", korean = "다리" },
  { label = "v04_watch_rom_057d4_스테이지_8c", category = "스테이지", rom = 0x057D4, start = 0x97C4, stop = 0x97C8, bytes = "8B 8C", old_bytes = "A6 98", source = "はし", korean = "다리" },
  { label = "v04_rom_07227_candidate_84", category = "무기", rom = 0x07227, start = 0xB216, stop = 0xB21A, bytes = "88 89 8A", old_bytes = "8A 94 99", source = "カタナ", korean = "카타나" },
  { label = "v04_rom_0736a_candidate_93", category = "UI", rom = 0x0736A, start = 0xB359, stop = 0xB35E, bytes = "96 8E 97", old_bytes = "BB 95 AF", source = "ライフ", korean = "라이프" },
  { label = "v04_rom_0739d_candidate_93", category = "UI", rom = 0x0739D, start = 0xB38C, stop = 0xB391, bytes = "96 8E 97", old_bytes = "BB 95 AF", source = "ライフ", korean = "라이프" },
}
