#!/usr/bin/env python3
"""Generate route-specific FCEUX target tables and watcher wrappers."""

from __future__ import annotations

import json
from pathlib import Path

from rom_utils import REPO_ROOT


ROUTES_JSON = REPO_ROOT / "rom_analysis" / "manual_proof_routes.json"
LUA_DIR = REPO_ROOT / "lua"
OUT_JSON = REPO_ROOT / "rom_analysis" / "route_fceux_targets.json"
OUT_MD = REPO_ROOT / "rom_analysis" / "route_fceux_targets.md"


def lua_quote(value: object) -> str:
    text = str(value)
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def parse_cpu_start(row: dict[str, object]) -> int:
    # Bank 1 PRG ROM offsets map to CPU $8000-$BFFF in the current target model.
    return 0x8000 + (int(str(row["rom_offset"]), 16) - 0x4000)


def parse_bytes(values: list[str]) -> str:
    return " ".join(part[2:].upper() if part.lower().startswith("0x") else part.upper() for part in values)


def slug(value: str) -> str:
    return "".join(ch.lower() if ch.isalnum() else "_" for ch in value).strip("_")


def target_for(route: dict[str, object], row: dict[str, object]) -> dict[str, object]:
    start = parse_cpu_start(row)
    byte_count = int(row["source_byte_len"])
    offset_slug = str(row["rom_offset"]).replace("0x", "").lower()
    romaji_slug = slug(str(row["romaji"]))
    return {
        "label": f"broad_{offset_slug}_{romaji_slug}",
        "route": route["route"],
        "group": route["group"],
        "romaji": row["romaji"],
        "rom_offset": row["rom_offset"],
        "start": start,
        "stop": start + byte_count - 1,
        "expected_original_bytes": "",
        "old_bytes": "",
        "future_patch_bytes_preview": parse_bytes(list(row["planned_prg_bytes_after_batch46"])),
        "confidence": row["confidence"],
        "screen_hint": row["screen_hint"],
    }


def make_payload() -> dict[str, object]:
    route_payload = json.loads(ROUTES_JSON.read_text(encoding="utf-8"))
    routes = []
    all_targets = []
    for route in route_payload["routes"]:
        targets = [target_for(route, row) for row in route["candidates"]]
        for target, row in zip(targets, route["candidates"]):
            # Keep original bytes in a second pass so JSON stays close to the route source.
            target["expected_original_bytes"] = ""
            target["old_bytes"] = ""
            if "planned_prg_bytes_after_batch46" in row:
                target["future_patch_bytes_preview"] = parse_bytes(list(row["planned_prg_bytes_after_batch46"]))
        routes.append(
            {
                "route": route["route"],
                "group": route["group"],
                "target_lua": f"lua/kunio_route_{slug(str(route['group']))}_targets.lua",
                "watcher_lua": f"lua/kunio_manual_route_{slug(str(route['group']))}_capture_watch.lua",
                "target_count": len(targets),
                "rom_offsets": [target["rom_offset"] for target in targets],
                "targets": targets,
            }
        )
        all_targets.extend(targets)
    return {
        "source": str(ROUTES_JSON.relative_to(REPO_ROOT)),
        "summary": {
            "route_count": len(routes),
            "target_count": len(all_targets),
            "rule": "Route-specific watchers reduce manual dump noise; run on the base Japanese ROM.",
        },
        "routes": routes,
    }


def original_bytes_by_offset() -> dict[str, str]:
    readiness = json.loads((REPO_ROOT / "rom_analysis" / "batch46_text_readiness.json").read_text(encoding="utf-8"))
    by_offset = {}
    for row in readiness["screen_proof_candidates"]:
        # The route source only carries lengths; keep original bytes from broad_scan_patchability.
        by_offset[str(row["rom_offset"])] = ""
    broad = json.loads((REPO_ROOT / "rom_analysis" / "broad_scan_patchability.json").read_text(encoding="utf-8"))
    for row in broad["promotion_candidates"]:
        by_offset[str(row["rom_offset"])] = str(row["bytes"])
    return by_offset


def write_route_lua(route: dict[str, object], original_by_offset: dict[str, str]) -> None:
    path = REPO_ROOT / route["target_lua"]
    lines = [
        "-- Auto-generated by scripts/generate_route_fceux_targets.py.",
        f"-- Route {route['route']}: {route['group']}",
        "-- Use on the base ROM; proof still requires visible screen context.",
        "return {",
    ]
    for target in route["targets"]:
        original = original_by_offset[target["rom_offset"]]
        target["expected_original_bytes"] = original
        target["old_bytes"] = original
        lines.append(
            "  { "
            f"label = {lua_quote(target['label'])}, "
            f"category = {lua_quote(target['group'])}, "
            f"rom = 0x{int(str(target['rom_offset']), 16):05X}, "
            f"start = 0x{target['start']:04X}, "
            f"stop = 0x{target['stop']:04X}, "
            f"bytes = {lua_quote(original)}, "
            f"old_bytes = {lua_quote(original)}, "
            f"source = {lua_quote(target['group'])}, "
            f"romaji = {lua_quote(target['romaji'])}, "
            f"korean = {lua_quote(target['group'])}, "
            f"confidence = {lua_quote(target['confidence'])} "
            "},"
        )
    lines.append("}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_watcher(route: dict[str, object]) -> None:
    path = REPO_ROOT / route["watcher_lua"]
    target_name = Path(route["target_lua"]).name
    lines = [
        f"-- Auto-generated route watcher for {route['group']}.",
        "local function script_dir()",
        '    local source = debug.getinfo(1, "S").source or ""',
        '    if string.sub(source, 1, 1) == "@" then',
        "        source = string.sub(source, 2)",
        "    end",
        '    local dir = string.match(source, "^(.*)[/\\\\][^/\\\\]+$")',
        '    return dir or "."',
        "end",
        "",
        "local LUA_DIR = script_dir()",
        'local ROOT_DIR = string.match(LUA_DIR, "^(.*)[/\\\\]lua$") or "."',
        "",
        f'KUNIO_TARGETS_LUA = LUA_DIR .. "/{target_name}"',
        'KUNIO_MANUAL_DUMP_OUTPUT = ROOT_DIR .. "/rom_analysis/manual_screen_dump_broad_scan"',
        "",
        'dofile(LUA_DIR .. "/kunio_manual_capture_watch.lua")',
    ]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_markdown(payload: dict[str, object]) -> None:
    lines = [
        "# Route FCEUX Targets",
        "",
        "These route-specific target tables and watcher wrappers narrow the manual broad-scan proof pass to one screen context at a time.",
        "",
        f"- Routes: **{payload['summary']['route_count']}**",
        f"- Targets: **{payload['summary']['target_count']}**",
        "",
        "## Route Watchers",
        "",
        "| route | group | targets | target lua | watcher lua | ROM offsets |",
        "| ---: | --- | ---: | --- | --- | --- |",
    ]
    for route in payload["routes"]:
        lines.append(
            f"| {route['route']} | {route['group']} | {route['target_count']} | "
            f"`{route['target_lua']}` | `{route['watcher_lua']}` | "
            f"`{', '.join(route['rom_offsets'])}` |"
        )
    lines += [
        "",
        "## Rule",
        "",
        "- Run these watchers on the base Japanese ROM.",
        "- Press `D` only after manually reaching the matching route screen.",
        "- Use `python scripts/analyze_broad_scan_manual_dump.py` after capture.",
        "- A route hit is still not patch approval unless the visible screen context matches.",
    ]
    OUT_MD.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    payload = make_payload()
    original_by_offset = original_bytes_by_offset()
    for route in payload["routes"]:
        write_route_lua(route, original_by_offset)
        write_watcher(route)
    OUT_JSON.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    write_markdown(payload)
    print(f"Wrote {OUT_JSON}")
    print(f"Wrote {OUT_MD}")
    for route in payload["routes"]:
        print(f"Wrote {route['target_lua']}")
        print(f"Wrote {route['watcher_lua']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
