#!/usr/bin/env python3
"""Generate FCEUX read-watch targets for the v0.4 equal-length PRG experiment."""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
REPORT = ROOT / "output" / "kunio_period_drama_korean_prg_plan_v0.4_equal_length_static_build_report.json"
INVENTORY = ROOT / "rom_analysis" / "bank1_offset_inventory.json"
OUT_LUA = ROOT / "lua" / "kunio_v04_equal_length_targets.lua"
OUT_MD = ROOT / "rom_analysis" / "v04_equal_length_fceux_targets.md"
OUT_JSON = ROOT / "rom_analysis" / "v04_equal_length_fceux_targets.json"


def parse_hex_int(value: str) -> int:
    value = value.strip()
    if value.startswith("$"):
        return int(value[1:], 16)
    return int(value, 16)


def load_inventory_index() -> tuple[dict[str, dict[str, object]], dict[str, dict[str, object]]]:
    data = json.loads(INVENTORY.read_text(encoding="utf-8"))
    by_label = {}
    by_rom = {}
    for row in data.get("targets", []):
        by_label[str(row.get("label"))] = row
        by_rom[str(row.get("rom_hit")).upper()] = row
    return by_label, by_rom


def build_targets() -> dict[str, object]:
    report = json.loads(REPORT.read_text(encoding="utf-8"))
    by_label, by_rom = load_inventory_index()
    targets = []
    missing_inventory = []
    for row in report.get("applied", []):
        inv = by_label.get(str(row.get("label")))
        if inv is None:
            inv = by_rom.get(str(row.get("rom_hit")).upper())
        if inv is None:
            missing_inventory.append(row)
            continue
        cpu_start, cpu_stop = inv["record_cpu_range"]
        target = {
            "label": f"v04_{row['label']}",
            "source_label": row["label"],
            "category": inv.get("category", row.get("source", "")),
            "source": row.get("source"),
            "korean": row.get("korean"),
            "rom_hit": row.get("rom_hit"),
            "start": parse_hex_int(str(cpu_start)),
            "stop": parse_hex_int(str(cpu_stop)),
            "expected_patched_bytes": row.get("new_bytes"),
            "original_bytes": row.get("old_bytes"),
            "evidence_level": row.get("evidence_level"),
            "risk": row.get("risk"),
        }
        targets.append(target)

    targets.sort(key=lambda item: (int(str(item["rom_hit"]), 16), str(item["label"])))
    return {
        "source_report": str(REPORT.relative_to(ROOT)),
        "inventory": str(INVENTORY.relative_to(ROOT)),
        "patched_rom": report.get("patched_rom_path"),
        "patched_md5": report.get("patched_md5"),
        "target_count": len(targets),
        "missing_inventory_count": len(missing_inventory),
        "targets": targets,
        "missing_inventory": missing_inventory,
    }


def lua_quote(value: object) -> str:
    text = str(value)
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def write_lua(payload: dict[str, object]) -> None:
    lines = [
        "-- Auto-generated by scripts/generate_v04_fceux_targets.py.",
        "-- Targets expect patched PRG bytes from the v0.4 equal-length static experiment.",
        "return {",
    ]
    for target in payload["targets"]:
        lines.append(
            "  { "
            f"label = {lua_quote(target['label'])}, "
            f"category = {lua_quote(target['category'])}, "
            f"rom = 0x{int(str(target['rom_hit']), 16):05X}, "
            f"start = 0x{target['start']:04X}, "
            f"stop = 0x{target['stop']:04X}, "
            f"bytes = {lua_quote(target['expected_patched_bytes'])}, "
            f"old_bytes = {lua_quote(target['original_bytes'])}, "
            f"source = {lua_quote(target['source'])}, "
            f"korean = {lua_quote(target['korean'])} "
            "},"
        )
    lines.append("}")
    OUT_LUA.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_markdown(payload: dict[str, object]) -> None:
    lines = [
        "# v0.4 Equal-Length FCEUX Targets",
        "",
        "These targets watch for patched PRG bytes from the v0.4 equal-length static experiment.",
        "",
        f"- Source report: `{payload['source_report']}`",
        f"- Patched MD5: `{payload['patched_md5']}`",
        f"- Targets: `{payload['target_count']}`",
        f"- Missing inventory rows: `{payload['missing_inventory_count']}`",
        "",
        "Run with:",
        "",
        "```powershell",
        "python scripts/run_fceux_lua_analysis.py --rom output/kunio_period_drama_korean_prg_plan_v0.4_equal_length_static.nes --lua-script lua/kunio_bank1_watch.lua --target-lua lua/kunio_v04_equal_length_targets.lua --frames 10800 --timeout 240 --final-output rom_analysis/fceux_v04_equal_length_watch --clean-output --no-dump-hex --no-dump-bin",
        "```",
        "",
        "## Targets",
        "",
        "| ROM hit | CPU range | Japanese | Korean | category | evidence | old bytes | patched bytes |",
        "| --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for target in payload["targets"]:
        lines.append(
            f"| `{target['rom_hit']}` | `${target['start']:04X}-${target['stop']:04X}` | "
            f"{target['source']} | {target['korean']} | {target['category']} | "
            f"{target['evidence_level']} | `{target['original_bytes']}` | `{target['expected_patched_bytes']}` |"
        )
    lines.extend(
        [
            "",
            "## Notes",
            "",
            "- A hit with `active_expected_match=true` means the patched byte sequence is active in the watched CPU record.",
            "- Static/watch-range targets still need screen-state confirmation before being promoted to final patch offsets.",
            "- The overlapping `ROM+0x05644` candidate is not present here because the v0.4 builder skipped it in favor of `ROM+0x05643`.",
        ]
    )
    OUT_MD.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    payload = build_targets()
    OUT_JSON.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    write_lua(payload)
    write_markdown(payload)
    print(f"Wrote {OUT_LUA}")
    print(f"Wrote {OUT_MD}")
    print(f"Wrote {OUT_JSON}")
    print(f"targets={payload['target_count']} missing_inventory={payload['missing_inventory_count']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
