#!/usr/bin/env python3
"""Generate FCEUX read-watch targets for PRG padding experiment ROMs."""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
PLAN = ROOT / "rom_analysis" / "prg_padding_experiment_plan.json"
BUILD_REPORT = ROOT / "output" / "kunio_period_drama_korean_prg_padding_exp_build_report.json"
OUT_JSON = ROOT / "rom_analysis" / "prg_padding_fceux_targets.json"
OUT_MD = ROOT / "rom_analysis" / "prg_padding_fceux_targets.md"
OUT_LUA_DIR = ROOT / "lua"


def parse_hex_int(value: str) -> int:
    value = value.strip()
    if value.startswith("$"):
        return int(value[1:], 16)
    return int(value, 16)


def lua_quote(value: object) -> str:
    text = str(value)
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def load_builds_by_strategy() -> dict[str, dict]:
    report = json.loads(BUILD_REPORT.read_text(encoding="utf-8"))
    return {
        str(row["strategy"]): row
        for row in report.get("builds", [])
    }


def build_payload() -> dict[str, object]:
    plan = json.loads(PLAN.read_text(encoding="utf-8"))
    builds = load_builds_by_strategy()
    targets_by_strategy: dict[str, list[dict[str, object]]] = {}
    for row in plan.get("runtime_confirmed_first_targets", []):
        cpu_start = 0xB192
        cpu_stop = 0xB19C
        # Keep the exact CPU range from the inventory convention for ROM+0x071A4.
        for strategy in row.get("strategies", []):
            name = str(strategy["strategy"])
            build = builds.get(name, {})
            target = {
                "label": f"padding_{name}_{row['label']}",
                "source_label": row["label"],
                "strategy": name,
                "category": row.get("category"),
                "source": row.get("source"),
                "source_romaji": row.get("source_romaji", ""),
                "korean": row.get("korean"),
                "rom_hit": row.get("rom_hit"),
                "start": cpu_start,
                "stop": cpu_stop,
                "expected_patched_bytes": strategy["patched_bytes"],
                "original_bytes": row["original_bytes"],
                "pad_bytes": strategy["pad_bytes"],
                "rom_path": build.get("rom_path", ""),
                "patched_md5": build.get("patched_md5", ""),
            }
            targets_by_strategy.setdefault(name, []).append(target)

    return {
        "source": {
            "padding_plan": str(PLAN.relative_to(ROOT)),
            "build_report": str(BUILD_REPORT.relative_to(ROOT)),
        },
        "strategy_count": len(targets_by_strategy),
        "targets_by_strategy": targets_by_strategy,
    }


def write_lua(strategy: str, targets: list[dict[str, object]]) -> Path:
    path = OUT_LUA_DIR / f"kunio_padding_exp_{strategy}_targets.lua"
    lines = [
        "-- Auto-generated by scripts/generate_padding_fceux_targets.py.",
        f"-- Targets expect patched PRG bytes from the padding experiment strategy: {strategy}.",
        "return {",
    ]
    for target in targets:
        lines.append(
            "  { "
            f"label = {lua_quote(target['label'])}, "
            f"category = {lua_quote(target['category'])}, "
            f"rom = 0x{int(str(target['rom_hit']), 16):05X}, "
            f"start = 0x{target['start']:04X}, "
            f"stop = 0x{target['stop']:04X}, "
            f"bytes = {lua_quote(target['expected_patched_bytes'])}, "
            f"old_bytes = {lua_quote(target['original_bytes'])}, "
            f"source = {lua_quote(target['source'])}, "
            f"korean = {lua_quote(target['korean'])}, "
            f"strategy = {lua_quote(target['strategy'])} "
            "},"
        )
    lines.append("}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path


def write_markdown(payload: dict[str, object], lua_paths: dict[str, Path]) -> None:
    lines = [
        "# PRG Padding FCEUX Targets",
        "",
        "These targets verify that each padding experiment ROM has the expected patched bytes active in the `ROM+0x071A4` CPU record.",
        "",
        f"- Padding plan: `{payload['source']['padding_plan']}`",
        f"- Build report: `{payload['source']['build_report']}`",
        f"- Strategies: `{payload['strategy_count']}`",
        "",
        "## Targets",
        "",
        "| strategy | target lua | ROM | MD5 | ROM hit | CPU range | Japanese | Korean | old bytes | expected bytes |",
        "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for strategy, targets in payload["targets_by_strategy"].items():
        for target in targets:
            source = target["source"]
            if target.get("source_romaji"):
                source = f"{source} ({target['source_romaji']})"
            lines.append(
                f"| {strategy} | `{lua_paths[strategy].relative_to(ROOT)}` | "
                f"`{Path(str(target['rom_path'])).name}` | `{target['patched_md5']}` | "
                f"`{target['rom_hit']}` | `${target['start']:04X}-${target['stop']:04X}` | "
                f"{source} | {target['korean']} | `{target['original_bytes']}` | `{target['expected_patched_bytes']}` |"
            )
    lines += [
        "",
        "## Example Run",
        "",
        "```powershell",
        "python scripts/run_fceux_lua_analysis.py --rom output/kunio_period_drama_korean_prg_padding_exp_rom_071a4_candidate_82_pad_00.nes --lua-script lua/kunio_bank1_watch.lua --target-lua lua/kunio_padding_exp_pad_00_targets.lua --frames 3600 --timeout 120 --final-output rom_analysis/fceux_padding_exp_pad_00_watch --clean-output --no-dump-hex --no-dump-bin",
        "```",
        "",
        "A successful read-watch run should show `active_expected_match=true` for the selected strategy. Visual acceptance still requires checking the status UI in FCEUX.",
    ]
    OUT_MD.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    payload = build_payload()
    lua_paths = {
        strategy: write_lua(strategy, targets)
        for strategy, targets in payload["targets_by_strategy"].items()
    }
    serializable = {
        **payload,
        "lua_targets": {
            strategy: str(path.relative_to(ROOT))
            for strategy, path in lua_paths.items()
        },
    }
    OUT_JSON.write_text(json.dumps(serializable, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    write_markdown(payload, lua_paths)
    print(f"Wrote {OUT_JSON}")
    print(f"Wrote {OUT_MD}")
    for path in lua_paths.values():
        print(f"Wrote {path}")
    print(f"strategies={len(lua_paths)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
